export type Plant = {
  name: string;
  slug: string;
  category: "indoor" | "outdoor";
  emoji: string;
  light: string;
  water: string;
  difficulty: "Easy" | "Moderate" | "Hard";
  description: string;
  tags: string[];
  soil: string;
  humidity: string;
  temperature: string;
  fertilizing: string;
  propagation: string;
  commonProblems: string[];
  tips: string[];
  petSafe: boolean | null;
};

export const plants: Plant[] = [
  // ── Indoor ──────────────────────────────────────────────────────────────
  {
    name: "Monstera Deliciosa",
    slug: "monstera-deliciosa",
    category: "indoor",
    emoji: "🌿",
    light: "Bright indirect",
    water: "Weekly",
    difficulty: "Easy",
    description: "Iconic split-leaf tropical plant. Great for adding a lush, dramatic look indoors.",
    tags: ["tropical", "large", "popular"],
    soil: "Well-draining potting mix with perlite",
    humidity: "Medium to high (40–60%)",
    temperature: "18–27 °C (65–80 °F)",
    fertilizing: "Monthly in spring and summer with balanced liquid fertiliser",
    propagation: "Stem cuttings with a node placed in water or moist soil",
    commonProblems: ["Yellow leaves from overwatering", "Brown tips from low humidity", "No splits on leaves — needs more light"],
    tips: ["Wipe leaves with a damp cloth to keep them glossy", "Use a moss pole to support climbing growth", "Repot every 1–2 years in spring"],
    petSafe: false,
  },
  {
    name: "Snake Plant",
    slug: "snake-plant",
    category: "indoor",
    emoji: "🪴",
    light: "Low to bright indirect",
    water: "Every 2–3 weeks",
    difficulty: "Easy",
    description: "Nearly indestructible. Tolerates low light and irregular watering.",
    tags: ["low light", "drought tolerant", "beginner"],
    soil: "Fast-draining cactus or succulent mix",
    humidity: "Low to average (30–50%)",
    temperature: "15–29 °C (60–85 °F)",
    fertilizing: "2–3 times per year with a balanced fertiliser",
    propagation: "Division, leaf cuttings, or offsets",
    commonProblems: ["Root rot from overwatering", "Mushy base — reduce watering immediately", "Pale leaves — too much direct sun"],
    tips: ["Allow soil to fully dry between waterings", "One of the best air-purifying houseplants", "Thrives in almost any light condition"],
    petSafe: false,
  },
  {
    name: "Fiddle Leaf Fig",
    slug: "fiddle-leaf-fig",
    category: "indoor",
    emoji: "🌱",
    light: "Bright indirect",
    water: "Weekly",
    difficulty: "Moderate",
    description: "Trendy statement plant with large violin-shaped leaves. Needs consistency.",
    tags: ["large", "trendy"],
    soil: "Rich, well-draining potting mix",
    humidity: "Medium (40–60%)",
    temperature: "16–24 °C (60–75 °F)",
    fertilizing: "Monthly in spring and summer with a high-nitrogen fertiliser",
    propagation: "Stem cuttings in water or air layering",
    commonProblems: ["Brown spots from overwatering or root rot", "Leaf drop when moved — find a spot and leave it", "Dusty leaves blocking light"],
    tips: ["Never move it once it's happy — it sulks", "Keep away from drafts and vents", "Rotate quarterly for even growth"],
    petSafe: false,
  },
  {
    name: "Peace Lily",
    slug: "peace-lily",
    category: "indoor",
    emoji: "🌸",
    light: "Low to medium indirect",
    water: "Weekly",
    difficulty: "Easy",
    description: "One of the best low-light bloomers. White flowers and glossy foliage.",
    tags: ["low light", "flowering", "beginner"],
    soil: "Moist, well-draining all-purpose potting mix",
    humidity: "Medium to high (50–60%)",
    temperature: "18–27 °C (65–80 °F)",
    fertilizing: "Every 6 weeks in spring and summer with a bloom fertiliser",
    propagation: "Division at repotting time",
    commonProblems: ["Drooping leaves — needs water immediately", "Brown leaf tips — low humidity or fluoride in tap water", "No blooms — increase light slightly"],
    tips: ["Use filtered or rainwater if possible", "Will droop dramatically when thirsty but recovers quickly", "One of the top NASA air-purifying plants"],
    petSafe: false,
  },
  {
    name: "Pothos",
    slug: "pothos",
    category: "indoor",
    emoji: "🍃",
    light: "Low to medium indirect",
    water: "Weekly",
    difficulty: "Easy",
    description: "Fast-growing trailing vine perfect for shelves or hanging baskets.",
    tags: ["trailing", "low light", "beginner"],
    soil: "Standard potting mix — not fussy",
    humidity: "Any humidity level",
    temperature: "15–29 °C (60–85 °F)",
    fertilizing: "Every 2–3 months with a balanced fertiliser",
    propagation: "Stem cuttings in water — roots in 1–2 weeks",
    commonProblems: ["Yellow leaves from overwatering", "Leggy stems — needs more light", "Root rot if left in soggy soil"],
    tips: ["One of the easiest plants to propagate", "Trail from a shelf or train up a pole", "Golden pothos is especially forgiving of low light"],
    petSafe: false,
  },
  {
    name: "ZZ Plant",
    slug: "zz-plant",
    category: "indoor",
    emoji: "🌿",
    light: "Low to bright indirect",
    water: "Every 3–4 weeks",
    difficulty: "Easy",
    description: "Waxy, dark green leaves. Thrives on neglect and handles low light well.",
    tags: ["drought tolerant", "low light", "beginner"],
    soil: "Well-draining potting mix with added perlite",
    humidity: "Low to average — very tolerant",
    temperature: "15–24 °C (60–75 °F)",
    fertilizing: "2–3 times per year during the growing season",
    propagation: "Leaf cuttings (slow) or division of rhizomes",
    commonProblems: ["Yellow stems from overwatering", "Slow growth — this is normal", "Dusty leaves — wipe occasionally"],
    tips: ["Store water in its rhizomes — don't overwater", "Perfect for offices with no natural light", "Toxic — keep away from children and pets"],
    petSafe: false,
  },
  {
    name: "Rubber Plant",
    slug: "rubber-plant",
    category: "indoor",
    emoji: "🌳",
    light: "Bright indirect",
    water: "Every 1–2 weeks",
    difficulty: "Easy",
    description: "Bold glossy leaves in deep green or burgundy. A classic indoor tree.",
    tags: ["large", "classic"],
    soil: "Well-draining potting mix",
    humidity: "Medium (40–50%)",
    temperature: "15–27 °C (60–80 °F)",
    fertilizing: "Monthly in spring and summer",
    propagation: "Stem cuttings or air layering",
    commonProblems: ["Dropping leaves from overwatering or cold drafts", "Brown leaf edges from low humidity", "Leggy growth — prune to encourage bushiness"],
    tips: ["Wipe glossy leaves to keep them shining", "Burgundy varieties need more light to keep their colour", "Can grow very tall — prune to control height"],
    petSafe: false,
  },
  {
    name: "Spider Plant",
    slug: "spider-plant",
    category: "indoor",
    emoji: "🕷️",
    light: "Indirect light",
    water: "Weekly",
    difficulty: "Easy",
    description: "Produces arching leaves and trailing babies. Excellent air purifier.",
    tags: ["pet safe", "air purifier", "beginner"],
    soil: "Well-draining all-purpose potting mix",
    humidity: "Average (40–60%)",
    temperature: "13–27 °C (55–80 °F)",
    fertilizing: "Every 2 weeks in spring and summer",
    propagation: "Pot up the dangling plantlets (spiderettes)",
    commonProblems: ["Brown tips from fluoride in tap water — use filtered water", "Pale leaves — needs more light", "Drooping — underwatered"],
    tips: ["One of the most pet-safe houseplants", "Great for hanging baskets", "Spiderettes root easily in a small pot of soil"],
    petSafe: true,
  },
  {
    name: "Aloe Vera",
    slug: "aloe-vera",
    category: "indoor",
    emoji: "🌵",
    light: "Bright direct to indirect",
    water: "Every 3 weeks",
    difficulty: "Easy",
    description: "Succulent with gel-filled leaves. Keep on a sunny windowsill.",
    tags: ["succulent", "medicinal", "drought tolerant"],
    soil: "Cactus and succulent mix",
    humidity: "Low — tolerates dry air well",
    temperature: "13–27 °C (55–80 °F)",
    fertilizing: "Once or twice a year in spring",
    propagation: "Remove and pot up offsets (pups) from the base",
    commonProblems: ["Mushy brown leaves from overwatering", "Leggy and pale — needs more sun", "Red or orange tint — stressed from too much direct sun"],
    tips: ["Snap off a leaf and apply the gel to minor burns", "Plant in terracotta pots for better drainage", "Water deeply then let soil dry completely"],
    petSafe: false,
  },
  {
    name: "Orchid",
    slug: "orchid",
    category: "indoor",
    emoji: "💮",
    light: "Bright indirect",
    water: "Weekly (let roots dry between)",
    difficulty: "Moderate",
    description: "Elegant blooms that last for months. Needs good light and careful watering.",
    tags: ["flowering", "elegant"],
    soil: "Orchid bark mix — never regular potting soil",
    humidity: "Medium to high (50–70%)",
    temperature: "16–24 °C (60–75 °F)",
    fertilizing: "Weekly with diluted orchid fertiliser when in growth",
    propagation: "Keikis (baby plants that form on the flower spike)",
    commonProblems: ["Yellow leaves from overwatering", "No reblooming — needs a cool night temperature drop", "Root rot from sitting in water"],
    tips: ["Plant in a clear pot to monitor root health", "After blooming, cut the spike to a node to encourage reblooming", "Mist roots lightly rather than soaking"],
    petSafe: true,
  },
  {
    name: "Chinese Evergreen",
    slug: "chinese-evergreen",
    category: "indoor",
    emoji: "🌿",
    light: "Low to medium indirect",
    water: "Every 1–2 weeks",
    difficulty: "Easy",
    description: "Colorful patterned leaves. One of the most adaptable houseplants.",
    tags: ["low light", "colorful", "beginner"],
    soil: "Slightly acidic, well-draining potting mix",
    humidity: "Average to high",
    temperature: "16–27 °C (60–80 °F)",
    fertilizing: "Every 2 months during the growing season",
    propagation: "Stem cuttings or division",
    commonProblems: ["Yellow leaves from overwatering", "Brown edges from cold drafts or dry air", "Pest susceptibility — check under leaves"],
    tips: ["More colourful varieties need brighter light to maintain their pattern", "Avoid cold windowsills in winter", "Excellent for offices and dim corners"],
    petSafe: false,
  },
  {
    name: "Boston Fern",
    slug: "boston-fern",
    category: "indoor",
    emoji: "🌱",
    light: "Bright indirect",
    water: "Keep soil consistently moist",
    difficulty: "Moderate",
    description: "Lush, feathery fronds. Loves humidity — great for bathrooms.",
    tags: ["pet safe", "humidity", "lush"],
    soil: "Moist, peat-based or coco coir potting mix",
    humidity: "High (50–80%)",
    temperature: "15–24 °C (60–75 °F)",
    fertilizing: "Monthly in spring and summer with a balanced fertiliser",
    propagation: "Division in spring",
    commonProblems: ["Fronds turning yellow and dropping — dry air or underwatering", "Brown crispy tips — low humidity", "Scale insects — check stems and fronds"],
    tips: ["Run a humidifier nearby or place on a pebble tray with water", "Perfect for bathrooms with natural light", "Mist fronds daily in dry climates"],
    petSafe: true,
  },
  {
    name: "Calathea",
    slug: "calathea",
    category: "indoor",
    emoji: "🍃",
    light: "Low to medium indirect",
    water: "Weekly — keep lightly moist",
    difficulty: "Hard",
    description: "Stunning patterned leaves that fold up at night. Needs humidity.",
    tags: ["patterned", "humidity", "decorative"],
    soil: "Moist, well-draining mix with peat or coco coir",
    humidity: "High (60–80%)",
    temperature: "18–24 °C (65–75 °F)",
    fertilizing: "Monthly in spring and summer with a diluted balanced fertiliser",
    propagation: "Division at repotting time",
    commonProblems: ["Crispy brown edges — low humidity or tap water minerals", "Curling leaves — underwatered or too much light", "Yellow leaves — overwatering"],
    tips: ["Always use filtered or distilled water", "Place near a humidifier", "Leaves fold up at night — this is normal and called nyctinasty"],
    petSafe: true,
  },
  {
    name: "Dracaena",
    slug: "dracaena",
    category: "indoor",
    emoji: "🪴",
    light: "Low to bright indirect",
    water: "Every 2 weeks",
    difficulty: "Easy",
    description: "Spiky architectural plant available in many varieties. Very forgiving.",
    tags: ["low light", "architectural", "beginner"],
    soil: "Loamy, well-draining potting mix",
    humidity: "Low to average",
    temperature: "16–24 °C (60–75 °F)",
    fertilizing: "2–3 times a year with a balanced liquid fertiliser",
    propagation: "Stem tip or cane cuttings",
    commonProblems: ["Brown leaf tips from fluoride — use filtered water", "Yellow leaves from overwatering", "Leggy growth — prune the top and it will branch"],
    tips: ["One of the best plants for removing indoor air toxins", "Avoid cold drafts — sensitive to temperature drops", "Many varieties to choose from: Marginata, Massangeana, Warneckii"],
    petSafe: false,
  },
  {
    name: "Heartleaf Philodendron",
    slug: "heartleaf-philodendron",
    category: "indoor",
    emoji: "💚",
    light: "Low to medium indirect",
    water: "Weekly",
    difficulty: "Easy",
    description: "Vining plant with heart-shaped leaves. Grows quickly and looks great trailing.",
    tags: ["trailing", "low light", "beginner"],
    soil: "Standard potting mix",
    humidity: "Average to high",
    temperature: "16–27 °C (60–80 °F)",
    fertilizing: "Monthly in spring and summer",
    propagation: "Stem cuttings in water — very easy",
    commonProblems: ["Yellow leaves from overwatering", "Leggy growth — more light needed", "Small leaves — increase humidity and feeding"],
    tips: ["One of the fastest growing beginner plants", "Looks beautiful cascading from a shelf", "Easy to propagate — great for sharing cuttings"],
    petSafe: false,
  },
  {
    name: "Bird of Paradise",
    slug: "bird-of-paradise",
    category: "indoor",
    emoji: "🌺",
    light: "Bright direct to indirect",
    water: "Weekly",
    difficulty: "Moderate",
    description: "Dramatic large leaves. Needs lots of sunlight to thrive indoors.",
    tags: ["large", "tropical", "dramatic"],
    soil: "Rich, well-draining potting mix",
    humidity: "Medium to high (50–70%)",
    temperature: "18–30 °C (65–85 °F)",
    fertilizing: "Monthly in spring and summer with a balanced fertiliser",
    propagation: "Division of mature clumps",
    commonProblems: ["Split or torn leaves — normal from air movement or handling", "No growth — needs more light or bigger pot", "Brown edges — underwatered or low humidity"],
    tips: ["Needs at least 4 hours of direct sun to thrive", "Clean large leaves regularly", "May take 3–5 years to bloom indoors"],
    petSafe: false,
  },

  // ── Outdoor ─────────────────────────────────────────────────────────────
  {
    name: "Lavender",
    slug: "lavender",
    category: "outdoor",
    emoji: "💜",
    light: "Full sun (6+ hours)",
    water: "Every 2 weeks once established",
    difficulty: "Easy",
    description: "Fragrant purple spikes beloved by pollinators. Drought-tolerant once established.",
    tags: ["fragrant", "drought tolerant", "pollinators"],
    soil: "Sandy, alkaline, well-draining soil",
    humidity: "Low — hates wet conditions",
    temperature: "Frost hardy; best in –15 to 40 °C",
    fertilizing: "Minimal — a light top-dress of compost in spring",
    propagation: "Softwood or semi-hardwood cuttings in summer",
    commonProblems: ["Root rot in heavy or clay soil", "Woody and leggy — needs annual pruning", "Poor flowering — needs more sun"],
    tips: ["Prune by one third after flowering to keep compact", "Plant in raised beds if drainage is poor", "Harvest flowers just before they open for the strongest fragrance"],
    petSafe: true,
  },
  {
    name: "Rose",
    slug: "rose",
    category: "outdoor",
    emoji: "🌹",
    light: "Full sun (6+ hours)",
    water: "Twice weekly at the base",
    difficulty: "Moderate",
    description: "Classic garden flower with hundreds of varieties. Rewarding but needs attention.",
    tags: ["flowering", "classic", "fragrant"],
    soil: "Rich, loamy, well-draining soil; pH 6.0–6.5",
    humidity: "Medium — avoid wetting foliage",
    temperature: "Best in 15–26 °C (60–80 °F)",
    fertilizing: "Every 4–6 weeks from spring to late summer with a rose-specific fertiliser",
    propagation: "Hardwood cuttings in autumn",
    commonProblems: ["Black spot fungal disease", "Aphid infestations on new growth", "Powdery mildew in humid conditions"],
    tips: ["Water at the base — wet leaves invite disease", "Deadhead spent blooms to encourage more flowers", "Apply a thick mulch to retain moisture and suppress weeds"],
    petSafe: true,
  },
  {
    name: "Sunflower",
    slug: "sunflower",
    category: "outdoor",
    emoji: "🌻",
    light: "Full sun",
    water: "Weekly — deeply",
    difficulty: "Easy",
    description: "Cheerful annual that grows fast and tall. Great for cutting gardens.",
    tags: ["annual", "tall", "pollinator"],
    soil: "Well-draining soil — not too rich",
    humidity: "Tolerates a range",
    temperature: "Frost tender; sow after last frost",
    fertilizing: "Low nitrogen; too much nitrogen promotes leaves over flowers",
    propagation: "Direct sow seeds after last frost",
    commonProblems: ["Powdery mildew in humid conditions", "Birds and squirrels eating seeds", "Bending or falling — stake tall varieties"],
    tips: ["Plant in rows for a windbreak effect", "Save seeds from open-pollinated varieties for next year", "Faces east in the morning and tracks the sun when young"],
    petSafe: true,
  },
  {
    name: "Hydrangea",
    slug: "hydrangea",
    category: "outdoor",
    emoji: "💐",
    light: "Morning sun, afternoon shade",
    water: "Weekly — deeply",
    difficulty: "Easy",
    description: "Big showy blooms in blue, pink, or white. Colour depends on soil pH.",
    tags: ["flowering", "shade tolerant", "showy"],
    soil: "Moist, well-draining, humus-rich soil",
    humidity: "Moderate to high",
    temperature: "Hardy to –15 °C; protect from late frosts",
    fertilizing: "Balanced fertiliser in spring; avoid high-phosphorus",
    propagation: "Softwood cuttings in early summer",
    commonProblems: ["Wilting in afternoon heat — needs shade", "No flowers — pruned at wrong time", "Blue vs pink — lower soil pH (more acidic) = bluer flowers"],
    tips: ["Add aluminium sulphate to soil to make flowers bluer", "Prune bigleaf hydrangeas after flowering, not in spring", "Mulch heavily to retain moisture"],
    petSafe: false,
  },
  {
    name: "Oak Tree",
    slug: "oak-tree",
    category: "outdoor",
    emoji: "🌳",
    light: "Full sun",
    water: "Rainfall sufficient once established",
    difficulty: "Easy",
    description: "Long-lived native tree. Excellent wildlife habitat and shade provider.",
    tags: ["tree", "native", "shade"],
    soil: "Adaptable — prefers deep, well-draining loam",
    humidity: "Tolerates wide range",
    temperature: "Varies by species — most are very frost hardy",
    fertilizing: "Rarely needed — top-dress with compost every few years",
    propagation: "Acorns sown in autumn",
    commonProblems: ["Oak wilt fungal disease", "Gall wasps creating small lumps on leaves (usually harmless)", "Slow establishment in the first 2–3 years"],
    tips: ["Plant where it has space — oaks grow very large", "Supports hundreds of insect species", "Deep water in drought for the first 3 years"],
    petSafe: true,
  },
  {
    name: "Tomato",
    slug: "tomato",
    category: "outdoor",
    emoji: "🍅",
    light: "Full sun (8+ hours)",
    water: "Daily or every other day in summer",
    difficulty: "Moderate",
    description: "The ultimate edible garden plant. Needs regular watering and feeding.",
    tags: ["edible", "vegetable", "popular"],
    soil: "Rich, well-draining soil with added compost; pH 6.0–6.8",
    humidity: "Moderate — good airflow prevents disease",
    temperature: "18–29 °C (65–85 °F); frost tender",
    fertilizing: "High-potassium fertiliser once flowering starts",
    propagation: "Sow seeds indoors 6–8 weeks before last frost",
    commonProblems: ["Blossom end rot from calcium deficiency or irregular watering", "Blight — ensure good airflow", "Cracked fruit from uneven watering"],
    tips: ["Stake or cage all varieties", "Pinch out side shoots on cordon types", "Water at the base to prevent fungal disease"],
    petSafe: false,
  },
  {
    name: "Marigold",
    slug: "marigold",
    category: "outdoor",
    emoji: "🌼",
    light: "Full sun",
    water: "Weekly",
    difficulty: "Easy",
    description: "Cheerful orange and yellow blooms that deter pests. Brilliant companion plant.",
    tags: ["annual", "pest control", "companion"],
    soil: "Average, well-draining soil",
    humidity: "Tolerates dry conditions well",
    temperature: "Frost tender — plant out after last frost",
    fertilizing: "Minimal — too much nitrogen reduces flowering",
    propagation: "Direct sow or start indoors 4–6 weeks before last frost",
    commonProblems: ["Powdery mildew in humid conditions", "Legginess in shade", "Botrytis (grey mould) in wet weather"],
    tips: ["Plant near tomatoes and brassicas to repel pests", "Deadhead regularly for continuous blooms", "French marigolds are especially effective as companion plants"],
    petSafe: true,
  },
  {
    name: "Japanese Maple",
    slug: "japanese-maple",
    category: "outdoor",
    emoji: "🍁",
    light: "Partial shade to full sun",
    water: "Weekly, more in drought",
    difficulty: "Easy",
    description: "Stunning ornamental tree with delicate, colourful foliage.",
    tags: ["tree", "ornamental", "autumn colour"],
    soil: "Moist, well-draining, slightly acidic soil",
    humidity: "Moderate",
    temperature: "Hardy to –20 °C; protect from late spring frosts",
    fertilizing: "Once in early spring with a slow-release fertiliser",
    propagation: "Grafting or from seed (slow and variable)",
    commonProblems: ["Leaf scorch from afternoon sun or drought", "Late frost damage to new growth", "Verticillium wilt in poorly drained soil"],
    tips: ["Shelter from strong winds which can shred delicate leaves", "Autumn colour is most vivid with good sun and cool nights", "Containerised specimens are slower to establish but more manageable"],
    petSafe: true,
  },
  {
    name: "Boxwood",
    slug: "boxwood",
    category: "outdoor",
    emoji: "🌿",
    light: "Full sun to partial shade",
    water: "Weekly until established",
    difficulty: "Easy",
    description: "Dense evergreen shrub ideal for hedges and topiary.",
    tags: ["evergreen", "hedge", "formal"],
    soil: "Well-draining, slightly alkaline soil",
    humidity: "Average",
    temperature: "Hardy to –20 °C",
    fertilizing: "Once a year in spring with a slow-release balanced fertiliser",
    propagation: "Semi-hardwood cuttings in summer",
    commonProblems: ["Boxwood blight (fungal disease) — remove affected stems", "Box moth caterpillars — check regularly", "Winter bronzing — normal in cold weather, greens back in spring"],
    tips: ["Prune in late spring after new growth hardens", "Do not prune in late summer — new growth is vulnerable to frost", "Plant in groups for a formal hedge effect"],
    petSafe: false,
  },
  {
    name: "Daffodil",
    slug: "daffodil",
    category: "outdoor",
    emoji: "🌼",
    light: "Full sun to partial shade",
    water: "Rainfall usually sufficient",
    difficulty: "Easy",
    description: "Spring-flowering bulb. Plant in autumn for bright yellow blooms.",
    tags: ["bulb", "spring", "easy"],
    soil: "Well-draining soil — bulbs rot in waterlogged ground",
    humidity: "Average",
    temperature: "Need a cold period to bloom; hardy in most climates",
    fertilizing: "Top-dress with bulb fertiliser when shoots emerge in spring",
    propagation: "Divide bulb clumps every 3–4 years",
    commonProblems: ["No flowers — planted too shallow or bulbs exhausted", "Narcissus fly damage to bulbs", "Basal rot from waterlogged soil"],
    tips: ["Plant bulbs at 3x their depth in autumn", "Leave foliage to die back naturally — feeds the bulb for next year", "Naturalise in grass for a meadow effect"],
    petSafe: false,
  },
  {
    name: "Clematis",
    slug: "clematis",
    category: "outdoor",
    emoji: "🌸",
    light: "Full sun — but keep roots in shade",
    water: "Weekly",
    difficulty: "Moderate",
    description: "Vigorous climbing vine with large showy flowers. Perfect for fences and trellises.",
    tags: ["climber", "flowering", "fence"],
    soil: "Rich, moist, well-draining soil",
    humidity: "Average",
    temperature: "Most varieties hardy to –15 °C or below",
    fertilizing: "High-potassium fertiliser fortnightly during growing season",
    propagation: "Internodal cuttings in early summer",
    commonProblems: ["Clematis wilt — sudden collapse of stems (usually recovers from roots)", "Powdery mildew", "Slug damage to young shoots"],
    tips: ["The saying: 'head in the sun, feet in the shade' — mulch heavily over roots", "Pruning group depends on variety — check the label", "Provide a sturdy support — they grow heavy"],
    petSafe: true,
  },
  {
    name: "Hostas",
    slug: "hostas",
    category: "outdoor",
    emoji: "🍃",
    light: "Shade to partial shade",
    water: "Weekly — keep soil moist",
    difficulty: "Easy",
    description: "Bold foliage plants that thrive in shade. Come in dozens of varieties.",
    tags: ["shade", "foliage", "low maintenance"],
    soil: "Rich, moist, well-draining soil with lots of organic matter",
    humidity: "Medium to high",
    temperature: "Very frost hardy — die back in winter and return in spring",
    fertilizing: "Balanced fertiliser in early spring as shoots emerge",
    propagation: "Division in spring or autumn",
    commonProblems: ["Slug and snail damage — main enemy of hostas", "Leaf scorch in too much sun", "Crown rot in waterlogged soil"],
    tips: ["Use copper tape or slug pellets to protect leaves", "Slug-resistant varieties: Sum and Substance, Halcyon", "Divide clumps every 3–4 years to reinvigorate"],
    petSafe: false,
  },
  {
    name: "Peony",
    slug: "peony",
    category: "outdoor",
    emoji: "🌸",
    light: "Full sun (6+ hours)",
    water: "Weekly during dry spells",
    difficulty: "Easy",
    description: "Lush, fragrant blooms that return year after year. Long-lived perennial.",
    tags: ["perennial", "fragrant", "flowering"],
    soil: "Rich, well-draining, neutral to slightly alkaline soil",
    humidity: "Average",
    temperature: "Require cold winters to bloom; hardy to –30 °C",
    fertilizing: "Low-nitrogen fertiliser in early spring",
    propagation: "Division in autumn — each division needs at least 3 eyes",
    commonProblems: ["No flowers — planted too deep (eyes must be within 5 cm of surface)", "Botrytis blight in wet weather", "Ants on buds — they feed on nectar and are harmless"],
    tips: ["Plant the eyes no more than 5 cm (2 in) below soil surface", "Support heavy blooms with a peony ring", "Peonies can live for over 100 years in the right spot"],
    petSafe: false,
  },
  {
    name: "Black-eyed Susan",
    slug: "black-eyed-susan",
    category: "outdoor",
    emoji: "🌻",
    light: "Full sun",
    water: "Drought tolerant once established",
    difficulty: "Easy",
    description: "Native wildflower with golden petals and dark centres. Attracts butterflies.",
    tags: ["native", "wildflower", "pollinator"],
    soil: "Average to poor, well-draining soil",
    humidity: "Tolerates drought well",
    temperature: "Hardy perennial in most zones",
    fertilizing: "Rarely needed — rich soil promotes leaves over flowers",
    propagation: "Direct seed in spring or autumn; self-seeds readily",
    commonProblems: ["Powdery mildew in humid conditions", "Clumps become overcrowded — divide every 3 years", "Short-lived but self-seeds freely"],
    tips: ["Leave seed heads over winter for birds", "Excellent for naturalised meadow plantings", "Pairs beautifully with ornamental grasses"],
    petSafe: true,
  },
  {
    name: "Butterfly Bush",
    slug: "butterfly-bush",
    category: "outdoor",
    emoji: "🦋",
    light: "Full sun",
    water: "Weekly until established",
    difficulty: "Easy",
    description: "Fast-growing shrub covered in fragrant flower spikes that attract butterflies.",
    tags: ["shrub", "pollinator", "fragrant"],
    soil: "Well-draining, average to poor soil",
    humidity: "Tolerates dry conditions",
    temperature: "Hardy to –15 °C",
    fertilizing: "Light feed in spring — avoid overfeeding",
    propagation: "Softwood cuttings in early summer",
    commonProblems: ["Can be invasive — deadhead before seeds set", "Frost damage to stems — cut back hard in spring", "Poor flowering — needs full sun"],
    tips: ["Cut back hard every spring for the best flowering", "Deadhead spent spikes to extend the flowering season", "Check local regulations — considered invasive in some regions"],
    petSafe: true,
  },
];

export function getPlantBySlug(slug: string): Plant | undefined {
  return plants.find((p) => p.slug === slug);
}
